global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: exporter-metrics

rule_files:
- "prometheus.rules"

scrape_configs:
- job_name: development
  scrape_interval: 5s

  target_groups:
    # These endpoints are scraped via HTTP.
    - targets: ['localhost:9090','localhost:8080']